/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stcs.ui.member;

import stcs.bo.MemberBO;
import stcs.ui.Main;
import stcs.vo.MemberVO;

/**
 *
 * @author xiaob
 */
public class JFrame_MemberViewUI extends javax.swing.JFrame {

    public static String m_id;
    
    /**
     * Creates new form MemberViewUI
     */
    public JFrame_MemberViewUI(String m_id) {
        initComponents();
        this.m_id = m_id;
        findMember();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_m_name = new javax.swing.JLabel();
        Label_m_dorm = new javax.swing.JLabel();
        Label_m_qq = new javax.swing.JLabel();
        Label_m_dept = new javax.swing.JLabel();
        Label_m_state = new javax.swing.JLabel();
        Label_m_addtime = new javax.swing.JLabel();
        Label_m_major = new javax.swing.JLabel();
        Label_m_desc = new javax.swing.JLabel();
        Label_m_sex = new javax.swing.JLabel();
        Label_m_phone = new javax.swing.JLabel();
        Label_m_email = new javax.swing.JLabel();
        Label_m_post = new javax.swing.JLabel();
        Label_m_money = new javax.swing.JLabel();
        Label_m_leavetime = new javax.swing.JLabel();
        m_name = new javax.swing.JTextField();
        m_dorm = new javax.swing.JTextField();
        m_dept = new javax.swing.JTextField();
        m_qq = new javax.swing.JTextField();
        m_addtime = new javax.swing.JTextField();
        m_state = new javax.swing.JTextField();
        m_major = new javax.swing.JTextField();
        m_sex = new javax.swing.JTextField();
        m_phone = new javax.swing.JTextField();
        m_post = new javax.swing.JTextField();
        m_email = new javax.swing.JTextField();
        m_leavetime = new javax.swing.JTextField();
        m_money = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_desc = new javax.swing.JTextArea();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Label_m_name.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_name.setText("姓名：");

        Label_m_dorm.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_dorm.setText("宿舍：");

        Label_m_qq.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_qq.setText("QQ号码：");

        Label_m_dept.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_dept.setText("部门：");

        Label_m_state.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_state.setText("会员状态：");

        Label_m_addtime.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_addtime.setText("入会时间：");

        Label_m_major.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_major.setText("院系专业：");

        Label_m_desc.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_desc.setText("备注：");

        Label_m_sex.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_sex.setText("性别：");

        Label_m_phone.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_phone.setText("联系电话：");

        Label_m_email.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_email.setText("电子邮箱：");

        Label_m_post.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_post.setText("职务：");

        Label_m_money.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_money.setText("会费缴纳：");

        Label_m_leavetime.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Label_m_leavetime.setText("毕业时间：");

        m_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nameActionPerformed(evt);
            }
        });

        m_dorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_dormActionPerformed(evt);
            }
        });

        m_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_deptActionPerformed(evt);
            }
        });

        m_qq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_qqActionPerformed(evt);
            }
        });

        m_addtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_addtimeActionPerformed(evt);
            }
        });

        m_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_stateActionPerformed(evt);
            }
        });

        m_major.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_majorActionPerformed(evt);
            }
        });

        m_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_sexActionPerformed(evt);
            }
        });

        m_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_phoneActionPerformed(evt);
            }
        });

        m_post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_postActionPerformed(evt);
            }
        });

        m_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_emailActionPerformed(evt);
            }
        });

        m_leavetime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_leavetimeActionPerformed(evt);
            }
        });

        m_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_moneyActionPerformed(evt);
            }
        });

        m_desc.setColumns(20);
        m_desc.setRows(5);
        m_desc.setText("\n\n\n\n\n\n");
        jScrollPane1.setViewportView(m_desc);

        back.setText("返回");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_m_major)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m_major, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Label_m_desc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(Label_m_name)
                                .addGap(4, 4, 4)
                                .addComponent(m_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(Label_m_sex)
                                .addGap(4, 4, 4)
                                .addComponent(m_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(Label_m_dorm)
                                .addGap(4, 4, 4)
                                .addComponent(m_dorm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(Label_m_phone)
                                .addGap(4, 4, 4)
                                .addComponent(m_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(Label_m_qq)
                                .addGap(4, 4, 4)
                                .addComponent(m_qq, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(Label_m_email)
                                .addGap(4, 4, 4)
                                .addComponent(m_email, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(Label_m_dept)
                                .addGap(4, 4, 4)
                                .addComponent(m_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(Label_m_post)
                                .addGap(4, 4, 4)
                                .addComponent(m_post, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Label_m_state)
                                .addGap(4, 4, 4)
                                .addComponent(m_state, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(Label_m_money)
                                .addGap(4, 4, 4)
                                .addComponent(m_money, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Label_m_addtime)
                                .addGap(4, 4, 4)
                                .addComponent(m_addtime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(Label_m_leavetime)
                                .addGap(4, 4, 4)
                                .addComponent(m_leavetime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(back)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_m_name)
                            .addComponent(Label_m_sex))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_dorm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_m_dorm)
                            .addComponent(Label_m_phone))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_qq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_m_qq)
                            .addComponent(Label_m_email))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_m_dept)
                            .addComponent(Label_m_post))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_m_state)
                            .addComponent(Label_m_money))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_addtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_leavetime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_m_addtime)
                            .addComponent(Label_m_leavetime))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_major, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_m_major))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_m_desc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void m_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_nameActionPerformed

    private void m_dormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_dormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_dormActionPerformed

    private void m_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_deptActionPerformed

    private void m_qqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_qqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_qqActionPerformed

    private void m_addtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_addtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_addtimeActionPerformed

    private void m_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_stateActionPerformed

    private void m_majorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_majorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_majorActionPerformed

    private void m_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_sexActionPerformed

    private void m_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_phoneActionPerformed

    private void m_postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_postActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_postActionPerformed

    private void m_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_emailActionPerformed

    private void m_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_moneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_moneyActionPerformed

    private void m_leavetimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_leavetimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_leavetimeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main.memberView = null;
    }//GEN-LAST:event_backActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
        Main.memberView = null;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_MemberViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_MemberViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_MemberViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_MemberViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_MemberViewUI(m_id).setVisible(true);
            }
        });
    }

    
    public void findMember(){
        MemberBO bo = new MemberBO();
        MemberVO vo = bo.findMemberByM_id(m_id);
        m_name.setText(vo.getM_name());
        m_dorm.setText(vo.getM_dorm());
        m_dept.setText(vo.getM_dept());
        m_qq.setText(vo.getM_qq());
        m_addtime.setText(vo.getM_addtime());
        m_money.setText(vo.getM_money());
        m_state.setText(vo.getM_state());
        m_major.setText(vo.getM_major());
        m_sex.setText(vo.getM_sex());
        m_phone.setText(vo.getM_phone());
        m_post.setText(vo.getM_post());
        m_email.setText(vo.getM_email());
        m_leavetime.setText(vo.getM_leavetime());
        m_desc.setText(vo.getM_desc());
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_m_addtime;
    private javax.swing.JLabel Label_m_dept;
    private javax.swing.JLabel Label_m_desc;
    private javax.swing.JLabel Label_m_dorm;
    private javax.swing.JLabel Label_m_email;
    private javax.swing.JLabel Label_m_leavetime;
    private javax.swing.JLabel Label_m_major;
    private javax.swing.JLabel Label_m_money;
    private javax.swing.JLabel Label_m_name;
    private javax.swing.JLabel Label_m_phone;
    private javax.swing.JLabel Label_m_post;
    private javax.swing.JLabel Label_m_qq;
    private javax.swing.JLabel Label_m_sex;
    private javax.swing.JLabel Label_m_state;
    private javax.swing.JButton back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m_addtime;
    private javax.swing.JTextField m_dept;
    private javax.swing.JTextArea m_desc;
    private javax.swing.JTextField m_dorm;
    private javax.swing.JTextField m_email;
    private javax.swing.JTextField m_leavetime;
    private javax.swing.JTextField m_major;
    private javax.swing.JTextField m_money;
    private javax.swing.JTextField m_name;
    private javax.swing.JTextField m_phone;
    private javax.swing.JTextField m_post;
    private javax.swing.JTextField m_qq;
    private javax.swing.JTextField m_sex;
    private javax.swing.JTextField m_state;
    // End of variables declaration//GEN-END:variables
}
