/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stcs.ui;

import admin.JFrame_SocietyAddUI;
import admin.JFrame_SocietyUpdateUI;
import admin.JFrame_SocietyDeleteUI;
import admin.JFrame_SocietyViewUI;
import admin.JFrame_PasswordUpdateUI;

import admin.Function_SocietyTableModel;
import javax.swing.JOptionPane;
import static stcs.ui.Main.login;

/**
 *
 * @author Administrator
 */
public class AdminMenuUI extends javax.swing.JFrame {

    public static int admin_id;
    
    public static JFrame_SocietyAddUI societyAdd;
    public static JFrame_SocietyUpdateUI societyUpdate;
    public static JFrame_SocietyDeleteUI societyDelete;
    public static JFrame_SocietyViewUI societyView;
    public static JFrame_PasswordUpdateUI passUpdate;
    public Function_SocietyTableModel society_formModel = new Function_SocietyTableModel();

    /**
     * Creates new form AdminMenuUI
     */
    public AdminMenuUI(int admin_id) {
        initComponents();
        this.admin_id = admin_id;
        loadSocietyData();
        this.setLocationRelativeTo(null);
    }

    
    public void loadSocietyData (){
        society_formModel.setDataVector(society_formModel.findAll(),society_formModel.columnIdentifiers);
        Table_society_form.updateUI();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_passUpdate = new javax.swing.JButton();
        society_operation = new javax.swing.JPanel();
        society_operation_quit = new javax.swing.JButton();
        society_operation_add = new javax.swing.JButton();
        society_operation_view = new javax.swing.JButton();
        society_operation_update = new javax.swing.JButton();
        society_operation_delete = new javax.swing.JButton();
        society_form = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_society_form = new javax.swing.JTable();
        society_inquire = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_passUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reg/images/财务管理.png"))); // NOI18N
        button_passUpdate.setText("修改密码");
        button_passUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_passUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_passUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_passUpdateActionPerformed(evt);
            }
        });

        society_operation.setBackground(new java.awt.Color(0, 204, 204));
        society_operation.setBorder(javax.swing.BorderFactory.createTitledBorder("社团操作面板"));

        society_operation_quit.setText("退出");
        society_operation_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                society_operation_quitActionPerformed(evt);
            }
        });

        society_operation_add.setText("新增社团");
        society_operation_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                society_operation_addActionPerformed(evt);
            }
        });

        society_operation_view.setText("查看社团");
        society_operation_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                society_operation_viewActionPerformed(evt);
            }
        });

        society_operation_update.setText("修改社团");
        society_operation_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                society_operation_updateActionPerformed(evt);
            }
        });

        society_operation_delete.setText("删除社团");
        society_operation_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                society_operation_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout society_operationLayout = new javax.swing.GroupLayout(society_operation);
        society_operation.setLayout(society_operationLayout);
        society_operationLayout.setHorizontalGroup(
            society_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, society_operationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(society_operation_quit)
                .addContainerGap())
            .addGroup(society_operationLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(society_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(society_operation_delete)
                    .addComponent(society_operation_update)
                    .addComponent(society_operation_view)
                    .addComponent(society_operation_add))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        society_operationLayout.setVerticalGroup(
            society_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, society_operationLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(society_operation_add)
                .addGap(26, 26, 26)
                .addComponent(society_operation_view)
                .addGap(31, 31, 31)
                .addComponent(society_operation_update)
                .addGap(37, 37, 37)
                .addComponent(society_operation_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(society_operation_quit)
                .addGap(16, 16, 16))
        );

        society_form.setBackground(new java.awt.Color(0, 204, 204));
        society_form.setBorder(javax.swing.BorderFactory.createTitledBorder("社团表格"));

        Table_society_form.setModel(society_formModel);
        jScrollPane3.setViewportView(Table_society_form);

        javax.swing.GroupLayout society_formLayout = new javax.swing.GroupLayout(society_form);
        society_form.setLayout(society_formLayout);
        society_formLayout.setHorizontalGroup(
            society_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(society_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        society_formLayout.setVerticalGroup(
            society_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(society_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        society_inquire.setBackground(new java.awt.Color(0, 204, 204));
        society_inquire.setBorder(javax.swing.BorderFactory.createTitledBorder("社团查询面板"));

        jLabel9.setText("查找字段：");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "全部记录", "姓名", "会员状态", "会员缴费情况", "部门" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel10.setText("值为：");

        jButton13.setText("查询");

        javax.swing.GroupLayout society_inquireLayout = new javax.swing.GroupLayout(society_inquire);
        society_inquire.setLayout(society_inquireLayout);
        society_inquireLayout.setHorizontalGroup(
            society_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(society_inquireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap(431, Short.MAX_VALUE))
        );
        society_inquireLayout.setVerticalGroup(
            society_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(society_inquireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(society_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(society_inquire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(society_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(society_operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_passUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_passUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(society_inquire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(society_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(society_operation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void society_operation_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_society_operation_quitActionPerformed
        this.setVisible(false);
        login = new LoginUI(new javax.swing.JFrame(),true);
        login.setVisible(true);
    }//GEN-LAST:event_society_operation_quitActionPerformed

    private void society_operation_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_society_operation_addActionPerformed
        societyAdd = new JFrame_SocietyAddUI();
        societyAdd.setVisible(true);
    }//GEN-LAST:event_society_operation_addActionPerformed

    private void society_operation_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_society_operation_viewActionPerformed
        Object id;
        int row = Table_society_form.getSelectedRow();
        if(row >= Table_society_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要查看的社团！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_society_form.getColumn("社团id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_society_form.getValueAt(row, column);
            societyView = new JFrame_SocietyViewUI((String)id);
            societyView.setVisible(true);
        }
    }//GEN-LAST:event_society_operation_viewActionPerformed

    private void society_operation_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_society_operation_updateActionPerformed
        Object id;
        int row = Table_society_form.getSelectedRow();
        if(row >= Table_society_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要更新的社团！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_society_form.getColumn("社团id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_society_form.getValueAt(row, column);
            societyUpdate = new JFrame_SocietyUpdateUI((String)id);
            societyUpdate.setVisible(true);
        }
    }//GEN-LAST:event_society_operation_updateActionPerformed

    private void society_operation_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_society_operation_deleteActionPerformed
        Object id;
        int row = Table_society_form.getSelectedRow();
        if(row >= Table_society_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要删除的社团！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_society_form.getColumn("社团id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_society_form.getValueAt(row, column);
            societyDelete = new JFrame_SocietyDeleteUI((String)id);
            societyDelete.setVisible(true);
        }
    }//GEN-LAST:event_society_operation_deleteActionPerformed

    private void button_passUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_passUpdateActionPerformed
        passUpdate = new JFrame_PasswordUpdateUI(admin_id);
        passUpdate.setVisible(true);
    }//GEN-LAST:event_button_passUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenuUI(admin_id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_society_form;
    private javax.swing.JButton button_passUpdate;
    private javax.swing.JButton jButton13;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel society_form;
    private javax.swing.JPanel society_inquire;
    private javax.swing.JPanel society_operation;
    private javax.swing.JButton society_operation_add;
    private javax.swing.JButton society_operation_delete;
    private javax.swing.JButton society_operation_quit;
    private javax.swing.JButton society_operation_update;
    private javax.swing.JButton society_operation_view;
    // End of variables declaration//GEN-END:variables
}
