/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stcs.ui;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import stcs.bo.LoginBO;
import stcs.bo.SocietyBO;

/**
 *
 * @author xiaob
 */
public class LoginUI extends javax.swing.JDialog {

    /**
     * Creates new form LoginUI
     */
    public LoginUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ButtonGroup bg = new ButtonGroup();// 初始化按钮组
        bg.add(login_admin);// 加入按钮组
        bg.add(login_society);// 加入按钮组
        login_society.setSelected(true);// 默认选择
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        society_adminname = new javax.swing.JLabel();
        society_adminpass = new javax.swing.JLabel();
        society_adminName = new javax.swing.JTextField();
        society_adminPass = new javax.swing.JPasswordField();
        login_Button = new javax.swing.JButton();
        quit_Button = new javax.swing.JButton();
        createNew_Button = new javax.swing.JButton();
        login_admin = new javax.swing.JRadioButton();
        login_society = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        society_adminname.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        society_adminname.setText("登录账户：");

        society_adminpass.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        society_adminpass.setText("登录密码：");

        login_Button.setText("登录");
        login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_ButtonActionPerformed(evt);
            }
        });

        quit_Button.setText("退出");
        quit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_ButtonActionPerformed(evt);
            }
        });

        createNew_Button.setText("开通新社团");

        login_admin.setText("平台管理员");
        login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_adminActionPerformed(evt);
            }
        });

        login_society.setText("社团管理员");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(society_adminname)
                        .addGap(18, 18, 18)
                        .addComponent(society_adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(society_adminpass)
                            .addGap(18, 18, 18)
                            .addComponent(society_adminPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(login_Button)
                                    .addGap(18, 18, 18)
                                    .addComponent(quit_Button)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(login_admin)
                                    .addGap(56, 56, 56)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(login_society)
                                .addComponent(createNew_Button)))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(society_adminname)
                    .addComponent(society_adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(society_adminpass)
                    .addComponent(society_adminPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_admin)
                    .addComponent(login_society))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_Button)
                    .addComponent(quit_Button)
                    .addComponent(createNew_Button))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_ButtonActionPerformed
        // TODO add your handling code here:
        int id;
        String pass = new String(society_adminPass.getPassword());
        if("".equals(society_adminName.getText())){
            JOptionPane.showMessageDialog(this, "请输入用户名！", "警告", JOptionPane.WARNING_MESSAGE);
            society_adminName.requestFocus();
        }else if("".equals(pass)){
             JOptionPane.showMessageDialog(this, "请输入密码！", "警告", JOptionPane.WARNING_MESSAGE);
             society_adminPass.requestFocus();
        }else{
            id = Integer.parseInt(society_adminName.getText());
            LoginBO bo = new LoginBO();
            
            boolean rtn = false;
            if(login_admin.isSelected()){
                rtn = bo.doLogin_as_admin(id, pass);
                if(rtn){
                    this.setVisible(false);
                    Main.login = null;
                    Main.adminMenu = new AdminMenuUI(id);
                    Main.adminMenu.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(this, "你输入的用户名或密码不对！", "警告", JOptionPane.WARNING_MESSAGE);
                }
            }else if(login_society.isSelected()){
                rtn = bo.doLogin_as_society(id, pass);
                if(rtn){
                    this.setVisible(false);
                    Main.login = null;
                    Main.stMenu = new StMenuUI(id);
                    Main.stMenu.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(this, "你输入的用户名或密码不对！", "警告", JOptionPane.WARNING_MESSAGE);
                }
            }

            

        }
    }//GEN-LAST:event_login_ButtonActionPerformed

    private void quit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_ButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quit_ButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void login_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginUI dialog = new LoginUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNew_Button;
    private javax.swing.JButton login_Button;
    private javax.swing.JRadioButton login_admin;
    private javax.swing.JRadioButton login_society;
    private javax.swing.JButton quit_Button;
    private javax.swing.JTextField society_adminName;
    private javax.swing.JPasswordField society_adminPass;
    private javax.swing.JLabel society_adminname;
    private javax.swing.JLabel society_adminpass;
    // End of variables declaration//GEN-END:variables
}
