/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stcs.ui;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import stcs.ui.financial.Function_FinancialTableModel;
import stcs.ui.financial.JFrame_FinancialAddUI;
import stcs.ui.financial.JFrame_FinancialDeleteUI;
import stcs.ui.financial.JFrame_FinancialStatisticsUI;
import stcs.ui.financial.JFrame_FinancialUpdateUI;
import stcs.ui.financial.JFrame_FinancialViewUI;

import stcs.ui.member.Function_MemberTableModel;
import stcs.ui.member.JFrame_MemberViewUI;
import stcs.ui.member.JFrame_MemberAddUI;
import stcs.ui.member.JFrame_MemberUpdateUI;
import stcs.ui.member.JFrame_MemberDeleteUI;
import stcs.ui.setting.settingUI;

import stcs.ui.transaction.Function_TransactionTableModel;
import stcs.ui.transaction.JFrame_TransactionAddUI;
import stcs.ui.transaction.JFrame_TransactionViewUI;
import stcs.ui.transaction.JFrame_TransactionUpdateUI;
import stcs.ui.transaction.JFrame_TransactionDeleteUI;

/**
 *
 * @author xiaob
 */
public class StMenuUI extends javax.swing.JFrame {

    public static int st_id;
    
    /**
     * Creates new form StMenuUI
     */
    public StMenuUI(int st_id) {
        initComponents();
        this.st_id = st_id;
        loadMemberData();
        loadTransactionData();
        loadFinancialData();
    }
    
    public Function_MemberTableModel member_formModel = new Function_MemberTableModel();
    public Function_TransactionTableModel transaction_formModel = new Function_TransactionTableModel();
    public Function_FinancialTableModel financial_formModel = new Function_FinancialTableModel();


    
    public void loadMemberData (){
        member_formModel.setDataVector(member_formModel.findAll(),member_formModel.columnIdentifiers);
        Table_member_form.updateUI();
    }
    
    public void loadTransactionData (){
        transaction_formModel.setDataVector(transaction_formModel.findAll(),transaction_formModel.columnIdentifiers);
        Table_transaction_form.updateUI();
    }

    public void loadFinancialData (){
        financial_formModel.setDataVector(financial_formModel.findAll(),financial_formModel.columnIdentifiers);
        Table_financial_form.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        function = new javax.swing.JPanel();
        member_function_button = new javax.swing.JButton();
        transaction_function_button = new javax.swing.JButton();
        financial_function_button = new javax.swing.JButton();
        setting_function_button = new javax.swing.JButton();
        refresh_function_button1 = new javax.swing.JButton();
        inquire = new javax.swing.JPanel();
        member_inquire = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        transaction_inquire = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        financial_inquire = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        form = new javax.swing.JPanel();
        member_form = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_member_form = new javax.swing.JTable();
        transaction_form = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table_transaction_form = new javax.swing.JTable();
        financial_form = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_financial_form = new javax.swing.JTable();
        operation = new javax.swing.JPanel();
        member_operation = new javax.swing.JPanel();
        member_operation_add = new javax.swing.JButton();
        member_operation_view = new javax.swing.JButton();
        member_operation_update = new javax.swing.JButton();
        member_operation_delete = new javax.swing.JButton();
        member_operation_quit = new javax.swing.JButton();
        transaction_operation = new javax.swing.JPanel();
        transaction_operation_add = new javax.swing.JButton();
        transaction_operation_view = new javax.swing.JButton();
        transaction_operation_update = new javax.swing.JButton();
        transaction_operation_delete = new javax.swing.JButton();
        transaction_operation_quit = new javax.swing.JButton();
        financial_operation = new javax.swing.JPanel();
        financial_operation_quit = new javax.swing.JButton();
        financial_operation_add = new javax.swing.JButton();
        financial_operation_view = new javax.swing.JButton();
        financial_operation_update = new javax.swing.JButton();
        financial_operation_delete = new javax.swing.JButton();
        financial_operation_statistics = new javax.swing.JButton();
        state = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        function.setBackground(new java.awt.Color(204, 255, 204));
        function.setBorder(javax.swing.BorderFactory.createTitledBorder("导航栏"));

        member_function_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reg/images/会员管理.png"))); // NOI18N
        member_function_button.setText("会员管理");
        member_function_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        member_function_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        member_function_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_function_buttonActionPerformed(evt);
            }
        });

        transaction_function_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reg/images/社团管理.png"))); // NOI18N
        transaction_function_button.setText("事务管理");
        transaction_function_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transaction_function_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transaction_function_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_function_buttonActionPerformed(evt);
            }
        });

        financial_function_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reg/images/财务管理.png"))); // NOI18N
        financial_function_button.setText("财务管理");
        financial_function_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        financial_function_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        financial_function_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financial_function_buttonActionPerformed(evt);
            }
        });

        setting_function_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reg/images/系统设置.png"))); // NOI18N
        setting_function_button.setText("设置");
        setting_function_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        setting_function_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        setting_function_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setting_function_buttonActionPerformed(evt);
            }
        });

        refresh_function_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reg/images/刷新.png"))); // NOI18N
        refresh_function_button1.setText("刷新");
        refresh_function_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refresh_function_button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refresh_function_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_function_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout functionLayout = new javax.swing.GroupLayout(function);
        function.setLayout(functionLayout);
        functionLayout.setHorizontalGroup(
            functionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(member_function_button, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaction_function_button, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(financial_function_button, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setting_function_button, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refresh_function_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        functionLayout.setVerticalGroup(
            functionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(functionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(financial_function_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(member_function_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setting_function_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transaction_function_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refresh_function_button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        inquire.setLayout(new java.awt.CardLayout());

        member_inquire.setBackground(new java.awt.Color(204, 204, 255));
        member_inquire.setBorder(javax.swing.BorderFactory.createTitledBorder("会员信息查询面板"));

        jLabel1.setText("查找字段：");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "全部记录", "姓名", "会员状态", "会员缴费情况", "部门" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("值为：");

        jButton2.setText("查询");

        javax.swing.GroupLayout member_inquireLayout = new javax.swing.GroupLayout(member_inquire);
        member_inquire.setLayout(member_inquireLayout);
        member_inquireLayout.setHorizontalGroup(
            member_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(member_inquireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        member_inquireLayout.setVerticalGroup(
            member_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(member_inquireLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(member_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        inquire.add(member_inquire, "member_inquire_card");

        transaction_inquire.setBackground(new java.awt.Color(204, 255, 255));
        transaction_inquire.setBorder(javax.swing.BorderFactory.createTitledBorder("事务信息查询面板"));
        transaction_inquire.setPreferredSize(new java.awt.Dimension(576, 110));

        jLabel5.setText("查找字段：");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "全部记录", "姓名", "会员状态", "会员缴费情况", "部门" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel6.setText("值为：");

        jButton11.setText("查询");

        javax.swing.GroupLayout transaction_inquireLayout = new javax.swing.GroupLayout(transaction_inquire);
        transaction_inquire.setLayout(transaction_inquireLayout);
        transaction_inquireLayout.setHorizontalGroup(
            transaction_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaction_inquireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transaction_inquireLayout.setVerticalGroup(
            transaction_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaction_inquireLayout.createSequentialGroup()
                .addGroup(transaction_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        inquire.add(transaction_inquire, "transaction_inquire_card");

        financial_inquire.setBackground(new java.awt.Color(255, 204, 204));
        financial_inquire.setBorder(javax.swing.BorderFactory.createTitledBorder("财务查询面板"));

        jLabel9.setText("查找字段：");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "全部记录", "姓名", "会员状态", "会员缴费情况", "部门" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel10.setText("值为：");

        jButton13.setText("查询");

        javax.swing.GroupLayout financial_inquireLayout = new javax.swing.GroupLayout(financial_inquire);
        financial_inquire.setLayout(financial_inquireLayout);
        financial_inquireLayout.setHorizontalGroup(
            financial_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financial_inquireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        financial_inquireLayout.setVerticalGroup(
            financial_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financial_inquireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(financial_inquireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        inquire.add(financial_inquire, "financial_inquire_card");

        form.setBackground(new java.awt.Color(255, 204, 255));
        form.setLayout(new java.awt.CardLayout());

        member_form.setBackground(new java.awt.Color(204, 204, 255));
        member_form.setBorder(javax.swing.BorderFactory.createTitledBorder("会员查询列表"));

        Table_member_form.setModel(member_formModel);
        jScrollPane1.setViewportView(Table_member_form);

        javax.swing.GroupLayout member_formLayout = new javax.swing.GroupLayout(member_form);
        member_form.setLayout(member_formLayout);
        member_formLayout.setHorizontalGroup(
            member_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
        );
        member_formLayout.setVerticalGroup(
            member_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        form.add(member_form, "member_form_card");

        transaction_form.setBackground(new java.awt.Color(204, 255, 255));
        transaction_form.setBorder(javax.swing.BorderFactory.createTitledBorder("事务查询列表"));

        Table_transaction_form.setModel(transaction_formModel);
        jScrollPane5.setViewportView(Table_transaction_form);

        javax.swing.GroupLayout transaction_formLayout = new javax.swing.GroupLayout(transaction_form);
        transaction_form.setLayout(transaction_formLayout);
        transaction_formLayout.setHorizontalGroup(
            transaction_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaction_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                .addContainerGap())
        );
        transaction_formLayout.setVerticalGroup(
            transaction_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaction_formLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        form.add(transaction_form, "transaction_form_card");

        financial_form.setBackground(new java.awt.Color(255, 204, 204));
        financial_form.setBorder(javax.swing.BorderFactory.createTitledBorder("财务表格"));

        Table_financial_form.setModel(financial_formModel);
        jScrollPane3.setViewportView(Table_financial_form);

        javax.swing.GroupLayout financial_formLayout = new javax.swing.GroupLayout(financial_form);
        financial_form.setLayout(financial_formLayout);
        financial_formLayout.setHorizontalGroup(
            financial_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financial_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                .addContainerGap())
        );
        financial_formLayout.setVerticalGroup(
            financial_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financial_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        form.add(financial_form, "financial_form_card");

        operation.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton19AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        operation.setLayout(new java.awt.CardLayout());

        member_operation.setBackground(new java.awt.Color(204, 204, 255));
        member_operation.setBorder(javax.swing.BorderFactory.createTitledBorder("会员操作面板"));

        member_operation_add.setText("添加会员");
        member_operation_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_operation_addActionPerformed(evt);
            }
        });

        member_operation_view.setText("查看会员");
        member_operation_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_operation_viewActionPerformed(evt);
            }
        });

        member_operation_update.setText("修改会员");
        member_operation_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_operation_updateActionPerformed(evt);
            }
        });

        member_operation_delete.setText("删除会员");
        member_operation_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_operation_deleteActionPerformed(evt);
            }
        });

        member_operation_quit.setText("退出");
        member_operation_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_operation_quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout member_operationLayout = new javax.swing.GroupLayout(member_operation);
        member_operation.setLayout(member_operationLayout);
        member_operationLayout.setHorizontalGroup(
            member_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(member_operationLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(member_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(member_operation_delete)
                    .addComponent(member_operation_update)
                    .addComponent(member_operation_view)
                    .addComponent(member_operation_add))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, member_operationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(member_operation_quit))
        );
        member_operationLayout.setVerticalGroup(
            member_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(member_operationLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(member_operation_add)
                .addGap(18, 18, 18)
                .addComponent(member_operation_view)
                .addGap(25, 25, 25)
                .addComponent(member_operation_update)
                .addGap(18, 18, 18)
                .addComponent(member_operation_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(member_operation_quit))
        );

        operation.add(member_operation, "member_operation_card");

        transaction_operation.setBackground(new java.awt.Color(204, 255, 255));
        transaction_operation.setBorder(javax.swing.BorderFactory.createTitledBorder("事务操作面板"));

        transaction_operation_add.setText("新增事务项");
        transaction_operation_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_operation_addActionPerformed(evt);
            }
        });

        transaction_operation_view.setText("查看事务项");
        transaction_operation_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_operation_viewActionPerformed(evt);
            }
        });

        transaction_operation_update.setText("修改事务项");
        transaction_operation_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_operation_updateActionPerformed(evt);
            }
        });

        transaction_operation_delete.setText("删除事务项");
        transaction_operation_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_operation_deleteActionPerformed(evt);
            }
        });

        transaction_operation_quit.setText("退出");
        transaction_operation_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_operation_quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transaction_operationLayout = new javax.swing.GroupLayout(transaction_operation);
        transaction_operation.setLayout(transaction_operationLayout);
        transaction_operationLayout.setHorizontalGroup(
            transaction_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaction_operationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transaction_operation_quit)
                .addContainerGap())
            .addGroup(transaction_operationLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(transaction_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transaction_operation_delete)
                    .addComponent(transaction_operation_update)
                    .addComponent(transaction_operation_view)
                    .addComponent(transaction_operation_add))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        transaction_operationLayout.setVerticalGroup(
            transaction_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaction_operationLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(transaction_operation_add)
                .addGap(29, 29, 29)
                .addComponent(transaction_operation_view)
                .addGap(27, 27, 27)
                .addComponent(transaction_operation_update)
                .addGap(18, 18, 18)
                .addComponent(transaction_operation_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(transaction_operation_quit)
                .addGap(16, 16, 16))
        );

        operation.add(transaction_operation, "transaction_operation_card");

        financial_operation.setBackground(new java.awt.Color(255, 204, 204));
        financial_operation.setBorder(javax.swing.BorderFactory.createTitledBorder("财务操作面板"));

        financial_operation_quit.setText("退出");
        financial_operation_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financial_operation_quitActionPerformed(evt);
            }
        });

        financial_operation_add.setText("新增财务项");
        financial_operation_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financial_operation_addActionPerformed(evt);
            }
        });

        financial_operation_view.setText("查看财务项");
        financial_operation_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financial_operation_viewActionPerformed(evt);
            }
        });

        financial_operation_update.setText("修改财务项");
        financial_operation_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financial_operation_updateActionPerformed(evt);
            }
        });

        financial_operation_delete.setText("删除财务项");
        financial_operation_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financial_operation_deleteActionPerformed(evt);
            }
        });

        financial_operation_statistics.setText("收支统计");
        financial_operation_statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financial_operation_statisticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout financial_operationLayout = new javax.swing.GroupLayout(financial_operation);
        financial_operation.setLayout(financial_operationLayout);
        financial_operationLayout.setHorizontalGroup(
            financial_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financial_operationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(financial_operation_quit)
                .addContainerGap())
            .addGroup(financial_operationLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(financial_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(financial_operation_statistics)
                    .addGroup(financial_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(financial_operation_delete)
                        .addComponent(financial_operation_update)
                        .addComponent(financial_operation_view)
                        .addComponent(financial_operation_add)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        financial_operationLayout.setVerticalGroup(
            financial_operationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financial_operationLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(financial_operation_add)
                .addGap(26, 26, 26)
                .addComponent(financial_operation_view)
                .addGap(31, 31, 31)
                .addComponent(financial_operation_update)
                .addGap(37, 37, 37)
                .addComponent(financial_operation_delete)
                .addGap(31, 31, 31)
                .addComponent(financial_operation_statistics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(financial_operation_quit)
                .addGap(16, 16, 16))
        );

        operation.add(financial_operation, "financial_operation_card");

        state.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setText("社团管理系统 – 社团管理员端  |  ");

        jLabel4.setText("当前用户：学生会  |  ");

        javax.swing.GroupLayout stateLayout = new javax.swing.GroupLayout(state);
        state.setLayout(stateLayout);
        stateLayout.setHorizontalGroup(
            stateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stateLayout.setVerticalGroup(
            stateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stateLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(stateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(state, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(function, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inquire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(operation, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(function, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(inquire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(operation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void member_function_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_function_buttonActionPerformed
        //
        CardLayout card1 = (CardLayout)operation.getLayout();
        card1.show(operation, "member_operation_card");
        CardLayout card2 = (CardLayout)form.getLayout();
        card2.show(form, "member_form_card");
        CardLayout card3 = (CardLayout)inquire.getLayout();
        card3.show(inquire, "member_inquire_card");
    }//GEN-LAST:event_member_function_buttonActionPerformed

    private void financial_function_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financial_function_buttonActionPerformed
        CardLayout card1 = (CardLayout)operation.getLayout();
        card1.show(operation, "financial_operation_card");
        CardLayout card2 = (CardLayout)form.getLayout();
        card2.show(form, "financial_form_card");
        CardLayout card3 = (CardLayout)inquire.getLayout();
        card3.show(inquire, "financial_inquire_card");
    }//GEN-LAST:event_financial_function_buttonActionPerformed

    private void setting_function_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setting_function_buttonActionPerformed
        Main.setting = new settingUI(String.valueOf(st_id));
        Main.setting.setVisible(true);
    }//GEN-LAST:event_setting_function_buttonActionPerformed

    private void transaction_function_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_function_buttonActionPerformed
        //
        CardLayout card1 = (CardLayout)operation.getLayout();
        card1.show(operation, "transaction_operation_card");
        CardLayout card2 = (CardLayout)form.getLayout();
        card2.show(form, "transaction_form_card");
        CardLayout card3 = (CardLayout)inquire.getLayout();
        card3.show(inquire, "transaction_inquire_card");
    }//GEN-LAST:event_transaction_function_buttonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void member_operation_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_operation_viewActionPerformed

        Object id;
        int row = Table_member_form.getSelectedRow();
        if(row >= Table_member_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要操作的数据！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_member_form.getColumn("会员id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_member_form.getValueAt(row, column);
            Main.memberView = new JFrame_MemberViewUI((String)id);
            Main.memberView.setVisible(true);
        }
    }//GEN-LAST:event_member_operation_viewActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void transaction_operation_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_operation_addActionPerformed
        Main.transactionAdd = new JFrame_TransactionAddUI();
        Main.transactionAdd.setVisible(true);
    }//GEN-LAST:event_transaction_operation_addActionPerformed

    private void jButton19AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton19AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19AncestorAdded

    private void member_operation_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_operation_addActionPerformed
        Main.memberAdd = new JFrame_MemberAddUI();
        Main.memberAdd.setVisible(true);
    }//GEN-LAST:event_member_operation_addActionPerformed

    private void member_operation_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_operation_deleteActionPerformed

        Object id;
        int row = Table_member_form.getSelectedRow();
        if(row >= Table_member_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要删除的数据！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_member_form.getColumn("会员id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_member_form.getValueAt(row, column);
            Main.memberDelete = new JFrame_MemberDeleteUI((String)id);
            Main.memberDelete.setVisible(true);
        }
    }//GEN-LAST:event_member_operation_deleteActionPerformed

    private void member_operation_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_operation_updateActionPerformed

        Object id;
        int row = Table_member_form.getSelectedRow();
        if(row >= Table_member_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要更新的数据！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_member_form.getColumn("会员id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_member_form.getValueAt(row, column);
            Main.memberUpdate = new JFrame_MemberUpdateUI((String)id);
            Main.memberUpdate.setVisible(true);
        }
    }//GEN-LAST:event_member_operation_updateActionPerformed

    private void member_operation_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_operation_quitActionPerformed
        Main.stMenu.setVisible(false);
        Main.login = new LoginUI(new javax.swing.JFrame(),true);
        Main.login.setVisible(true);
    }//GEN-LAST:event_member_operation_quitActionPerformed

    private void refresh_function_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_function_button1ActionPerformed
        loadMemberData();
        loadTransactionData();
        loadFinancialData();
    }//GEN-LAST:event_refresh_function_button1ActionPerformed

    private void transaction_operation_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_operation_quitActionPerformed
        Main.stMenu.setVisible(false);
        Main.login = new LoginUI(new javax.swing.JFrame(),true);
        Main.login.setVisible(true);
    }//GEN-LAST:event_transaction_operation_quitActionPerformed

    private void transaction_operation_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_operation_viewActionPerformed
        Object id;
        int row = Table_transaction_form.getSelectedRow();
        if(row >= Table_transaction_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要查看的事务！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_transaction_form.getColumn("事务id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_transaction_form.getValueAt(row, column);
            Main.transactionView = new JFrame_TransactionViewUI((String)id);
            Main.transactionView.setVisible(true);
        }
    }//GEN-LAST:event_transaction_operation_viewActionPerformed

    private void transaction_operation_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_operation_updateActionPerformed
        Object id;
        int row = Table_transaction_form.getSelectedRow();
        if(row >= Table_transaction_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要更新的事务！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_transaction_form.getColumn("事务id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_transaction_form.getValueAt(row, column);
            Main.transactionUpdate = new JFrame_TransactionUpdateUI((String)id);
            Main.transactionUpdate.setVisible(true);
        }
    }//GEN-LAST:event_transaction_operation_updateActionPerformed

    private void transaction_operation_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_operation_deleteActionPerformed
        Object id;
        int row = Table_transaction_form.getSelectedRow();
        if(row >= Table_transaction_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要删除的事务！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_transaction_form.getColumn("事务id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_transaction_form.getValueAt(row, column);
            Main.transactionDelete = new JFrame_TransactionDeleteUI((String)id);
            Main.transactionDelete.setVisible(true);
        }
    }//GEN-LAST:event_transaction_operation_deleteActionPerformed

    private void financial_operation_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financial_operation_addActionPerformed
        Main.financialAdd = new JFrame_FinancialAddUI();
        Main.financialAdd.setVisible(true);
    }//GEN-LAST:event_financial_operation_addActionPerformed

    private void financial_operation_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financial_operation_viewActionPerformed
        Object id;
        int row = Table_financial_form.getSelectedRow();
        if(row >= Table_financial_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要查看的财务项！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_financial_form.getColumn("财务id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_financial_form.getValueAt(row, column);
            Main.financialView = new JFrame_FinancialViewUI((String)id);
            Main.financialView.setVisible(true);
        }
    }//GEN-LAST:event_financial_operation_viewActionPerformed

    private void financial_operation_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financial_operation_updateActionPerformed
        Object id;
        int row = Table_financial_form.getSelectedRow();
        if(row >= Table_financial_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要更新的财务项！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_financial_form.getColumn("财务id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_financial_form.getValueAt(row, column);
            Main.financialUpdate = new JFrame_FinancialUpdateUI((String)id);
            Main.financialUpdate.setVisible(true);
        }
    }//GEN-LAST:event_financial_operation_updateActionPerformed

    private void financial_operation_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financial_operation_deleteActionPerformed
        Object id;
        int row = Table_financial_form.getSelectedRow();
        if(row >= Table_financial_form.getModel().getRowCount() || row == -1){ //没有选择行
            JOptionPane.showMessageDialog(this, "请选择你要删除的财务项！", "警告", JOptionPane.WARNING_MESSAGE);
        }else{
            int column = Table_financial_form.getColumn("财务id").getModelIndex();//返回此列的模型索引。
            id = (Object)Table_financial_form.getValueAt(row, column);
            Main.financialDelete = new JFrame_FinancialDeleteUI((String)id);
            Main.financialDelete.setVisible(true);
        }
    }//GEN-LAST:event_financial_operation_deleteActionPerformed

    private void financial_operation_statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financial_operation_statisticsActionPerformed
        Main.financialStatistics = new JFrame_FinancialStatisticsUI();
        Main.financialStatistics.setVisible(true);
    }//GEN-LAST:event_financial_operation_statisticsActionPerformed

    private void financial_operation_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financial_operation_quitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_financial_operation_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StMenuUI(st_id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_financial_form;
    private javax.swing.JTable Table_member_form;
    private javax.swing.JTable Table_transaction_form;
    private javax.swing.JPanel financial_form;
    private javax.swing.JButton financial_function_button;
    private javax.swing.JPanel financial_inquire;
    private javax.swing.JPanel financial_operation;
    private javax.swing.JButton financial_operation_add;
    private javax.swing.JButton financial_operation_delete;
    private javax.swing.JButton financial_operation_quit;
    private javax.swing.JButton financial_operation_statistics;
    private javax.swing.JButton financial_operation_update;
    private javax.swing.JButton financial_operation_view;
    private javax.swing.JPanel form;
    private javax.swing.JPanel function;
    private javax.swing.JPanel inquire;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel member_form;
    private javax.swing.JButton member_function_button;
    private javax.swing.JPanel member_inquire;
    private javax.swing.JPanel member_operation;
    private javax.swing.JButton member_operation_add;
    private javax.swing.JButton member_operation_delete;
    private javax.swing.JButton member_operation_quit;
    private javax.swing.JButton member_operation_update;
    private javax.swing.JButton member_operation_view;
    private javax.swing.JPanel operation;
    private javax.swing.JButton refresh_function_button1;
    private javax.swing.JButton setting_function_button;
    private javax.swing.JPanel state;
    private javax.swing.JPanel transaction_form;
    private javax.swing.JButton transaction_function_button;
    private javax.swing.JPanel transaction_inquire;
    private javax.swing.JPanel transaction_operation;
    private javax.swing.JButton transaction_operation_add;
    private javax.swing.JButton transaction_operation_delete;
    private javax.swing.JButton transaction_operation_quit;
    private javax.swing.JButton transaction_operation_update;
    private javax.swing.JButton transaction_operation_view;
    // End of variables declaration//GEN-END:variables
}
