/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stcs.ui.setting;

import stcs.bo.SocietyBO;
import stcs.ui.Main;
import stcs.vo.SocietyVO;

/**
 *
 * @author xiaob
 */
public class sigle_SocietyViewUI extends javax.swing.JFrame {

    public static String st_id;
    
    /**
     * Creates new form MemberViewUI
     */
    public sigle_SocietyViewUI(String st_id) {
        initComponents();
        this.st_id = st_id;
        findSociety();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_lx_email = new javax.swing.JLabel();
        st_name = new javax.swing.JTextField();
        st_addtime = new javax.swing.JTextField();
        Label_st_school = new javax.swing.JLabel();
        Label_lx_name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        st_desc = new javax.swing.JTextArea();
        st_city = new javax.swing.JTextField();
        Label_st_name = new javax.swing.JLabel();
        lx_name = new javax.swing.JTextField();
        lx_email = new javax.swing.JTextField();
        Label_st_addtime = new javax.swing.JLabel();
        Label_lx_phone = new javax.swing.JLabel();
        Label_lx_qq = new javax.swing.JLabel();
        st_school = new javax.swing.JTextField();
        Label_st_desc = new javax.swing.JLabel();
        Label_st_city = new javax.swing.JLabel();
        lx_phone = new javax.swing.JTextField();
        lx_qq = new javax.swing.JTextField();
        Button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Label_lx_email.setText("联系人邮箱：");

        Label_st_school.setText("所属院校：");

        Label_lx_name.setText("联系人姓名：");

        st_desc.setColumns(20);
        st_desc.setRows(5);
        jScrollPane1.setViewportView(st_desc);

        Label_st_name.setText("社团名称：");

        lx_email.setToolTipText("");

        Label_st_addtime.setText("注册时间：");

        Label_lx_phone.setText("联系人电话：");

        Label_lx_qq.setText("联系人QQ：");

        st_school.setToolTipText("");

        Label_st_desc.setText("简要说明：");

        Label_st_city.setText("所在城市：");

        Button_back.setText("返回");
        Button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_st_school)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(st_school))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_st_city)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(st_city))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_st_name)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(st_name, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_st_addtime)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(st_addtime, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_lx_email)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lx_email))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_lx_phone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lx_phone))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_lx_name)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lx_name, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_lx_qq)
                                        .addGap(18, 18, 18)
                                        .addComponent(lx_qq, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Label_st_desc)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(Button_back)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_lx_name)
                            .addComponent(lx_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_lx_phone)
                            .addComponent(lx_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_lx_email)
                            .addComponent(lx_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lx_qq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_lx_qq)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_st_name)
                            .addComponent(st_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_st_city)
                            .addComponent(st_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_st_school)
                            .addComponent(st_school, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(st_addtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_st_addtime))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_st_desc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Button_back)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
        Main.singleSocietyView = null;
    }//GEN-LAST:event_formWindowClosed

    private void Button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_backActionPerformed
        this.setVisible(false);
        Main.singleSocietyView = null;
    }//GEN-LAST:event_Button_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sigle_SocietyViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sigle_SocietyViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sigle_SocietyViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sigle_SocietyViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sigle_SocietyViewUI(st_id).setVisible(true);
            }
        });
    }

    
    private void findSociety() {
        SocietyBO bo = new SocietyBO();
        SocietyVO vo = bo.findSocietyBySt_id(st_id);
        st_name.setText(vo.getSt_name());
        st_school.setText(vo.getSt_school());
        st_city.setText(vo.getSt_city());
        st_addtime.setText(vo.getSt_addtime());
        st_desc.setText(vo.getSt_desc());
        lx_name.setText(vo.getLx_name());
        lx_phone.setText(vo.getLx_phone());
        lx_email.setText(vo.getLx_email());
        lx_qq.setText(vo.getLx_qq());
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_back;
    private javax.swing.JLabel Label_lx_email;
    private javax.swing.JLabel Label_lx_name;
    private javax.swing.JLabel Label_lx_phone;
    private javax.swing.JLabel Label_lx_qq;
    private javax.swing.JLabel Label_st_addtime;
    private javax.swing.JLabel Label_st_city;
    private javax.swing.JLabel Label_st_desc;
    private javax.swing.JLabel Label_st_name;
    private javax.swing.JLabel Label_st_school;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lx_email;
    private javax.swing.JTextField lx_name;
    private javax.swing.JTextField lx_phone;
    private javax.swing.JTextField lx_qq;
    private javax.swing.JTextField st_addtime;
    private javax.swing.JTextField st_city;
    private javax.swing.JTextArea st_desc;
    private javax.swing.JTextField st_name;
    private javax.swing.JTextField st_school;
    // End of variables declaration//GEN-END:variables


}
