/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stcs.ui.financial;

import stcs.bo.FinancialBO;
import stcs.ui.Main;
import stcs.vo.FinancialVO;
import stcs.vo.SocietyVO;


/**
 *
 * @author xiaob
 */
public class JFrame_FinancialUpdateUI extends javax.swing.JFrame {

    public static String f_id;
    
    /**
     * Creates new form SocietyUpdateUI
     */
    public JFrame_FinancialUpdateUI(String f_id) {
        initComponents();
        this.f_id = f_id;
        findFinancial();
        this.setLocationRelativeTo(null);
    }

    public JFrame_FinancialUpdateUI() {
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f_recorder = new javax.swing.JTextField();
        f_associate = new javax.swing.JTextField();
        Label_f_type = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        f_desc = new javax.swing.JTextArea();
        Label_f_money = new javax.swing.JLabel();
        Label_f_date = new javax.swing.JLabel();
        Button_back = new javax.swing.JButton();
        Label_f_recorder = new javax.swing.JLabel();
        Button_sure = new javax.swing.JButton();
        Label_f_associate = new javax.swing.JLabel();
        Label_f_desc = new javax.swing.JLabel();
        f_type = new javax.swing.JTextField();
        f_money = new javax.swing.JTextField();
        f_date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Label_f_type.setText("财务类型：");

        f_desc.setColumns(20);
        f_desc.setRows(5);
        jScrollPane1.setViewportView(f_desc);

        Label_f_money.setText("财务金额：");

        Label_f_date.setText("日    期：");

        Button_back.setText("返回");
        Button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_backActionPerformed(evt);
            }
        });

        Label_f_recorder.setText("记录人：");

        Button_sure.setText("保存");
        Button_sure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_sureActionPerformed(evt);
            }
        });

        Label_f_associate.setText("支出申报人/收入来源：");

        Label_f_desc.setText("收支说明：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_f_desc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(Button_sure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_back))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Label_f_associate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(f_associate)
                            .addGap(2, 2, 2))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label_f_date)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(f_date))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label_f_type)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(f_type, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label_f_recorder)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(f_recorder))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label_f_money)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(f_money, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_f_money)
                            .addComponent(f_money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_f_recorder)
                            .addComponent(f_recorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_f_type)
                            .addComponent(f_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_f_date)
                            .addComponent(f_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_f_associate)
                            .addComponent(f_associate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_f_desc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_back)
                    .addComponent(Button_sure))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
        Main.financialUpdate = null;
    }//GEN-LAST:event_formWindowClosed

    private void Button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_backActionPerformed
        this.setVisible(false);
        Main.financialAdd = null;
    }//GEN-LAST:event_Button_backActionPerformed

    private void Button_sureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_sureActionPerformed
        updateFinancial();
    }//GEN-LAST:event_Button_sureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_FinancialUpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_FinancialUpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_FinancialUpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_FinancialUpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_FinancialUpdateUI().setVisible(true);
            }
        });
    }

    private void findFinancial() {
        FinancialBO bo = new FinancialBO();
        FinancialVO vo = bo.findFinancialByF_id(f_id);
        f_type.setText(vo.getF_type());
        f_money.setText(vo.getF_money());
        f_date.setText(vo.getF_date());
        f_associate.setText(vo.getF_associate());
        f_desc.setText(vo.getF_desc());
        f_recorder.setText(vo.getF_recorder());
        
    }
    
    
    
    private void updateFinancial() {
        FinancialVO vo = new FinancialVO();
        vo.setF_type(f_type.getText());
        vo.setF_money(f_money.getText());
        vo.setF_date(f_associate.getText());
        vo.setF_associate(f_associate.getText());
        vo.setF_desc(f_desc.getText());
        vo.setF_recorder(f_recorder.getText());
        
        FinancialBO bo = new FinancialBO();
        boolean update_rtn = bo.doUpdate(vo,f_id);
        
        JDialog_FinancialUpdateRTN rtnDialog = new JDialog_FinancialUpdateRTN(new javax.swing.JFrame(), true);
        if(update_rtn == true){
            this.setVisible(false);
            Main.financialUpdate = null;
            Main.stMenu.loadFinancialData();
            rtnDialog.setVisible(true);
        }else{
            rtnDialog.updateFailed();
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_back;
    private javax.swing.JButton Button_sure;
    private javax.swing.JLabel Label_f_associate;
    private javax.swing.JLabel Label_f_date;
    private javax.swing.JLabel Label_f_desc;
    private javax.swing.JLabel Label_f_money;
    private javax.swing.JLabel Label_f_recorder;
    private javax.swing.JLabel Label_f_type;
    private javax.swing.JTextField f_associate;
    private javax.swing.JTextField f_date;
    private javax.swing.JTextArea f_desc;
    private javax.swing.JTextField f_money;
    private javax.swing.JTextField f_recorder;
    private javax.swing.JTextField f_type;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
